<x-layouts.app title="Plan {{ $event->title }}">
    <x-page-header title="Plan: {{ $event->title }}" description="Track preparation work and communicate with {{ $event->registered_count }} registered student(s)."><a href="{{ route('events.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Back to events</a></x-page-header>

    <div class="grid gap-6 xl:grid-cols-2">
        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between gap-4"><div><h2 class="font-semibold text-slate-900">Preparation checklist</h2><p class="mt-1 text-sm text-slate-500">Operational work before the event starts.</p></div><span class="rounded-full bg-purple-50 px-2.5 py-1 text-xs font-semibold text-purple-700">{{ $event->tasks->whereNotNull('completed_at')->count() }}/{{ $event->tasks->count() }} complete</span></div>
            <x-form-errors />
            <form action="{{ route('events.tasks.store', $event) }}" method="POST" class="mt-5 space-y-3 rounded-xl bg-slate-50 p-4">@csrf<div class="grid gap-3 sm:grid-cols-2"><input name="title" value="{{ old('title') }}" required maxlength="255" class="rounded-lg border border-slate-300 p-2.5 text-sm sm:col-span-2" placeholder="Task title"><select name="priority" class="rounded-lg border border-slate-300 p-2.5 text-sm"><option value="low">Low priority</option><option value="medium" selected>Medium priority</option><option value="high">High priority</option></select><input name="due_date" type="date" value="{{ old('due_date') }}" class="rounded-lg border border-slate-300 p-2.5 text-sm"><textarea name="description" rows="2" maxlength="2000" class="rounded-lg border border-slate-300 p-2.5 text-sm sm:col-span-2" placeholder="Optional notes">{{ old('description') }}</textarea></div><button class="w-full rounded-lg bg-purple-600 px-4 py-2.5 text-sm font-semibold text-white">Add task</button></form>
            @if($event->tasks->isEmpty())<p class="mt-6 rounded-xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500">No preparation tasks yet.</p>@else<div class="mt-5 divide-y divide-slate-100">@foreach($event->tasks as $task)<div class="flex items-start gap-3 py-4"><form action="{{ route('events.tasks.toggle', [$event, $task]) }}" method="POST">@csrf @method('PATCH')<button class="mt-0.5 grid h-6 w-6 place-items-center rounded-full border {{ $task->completed_at ? 'border-emerald-500 bg-emerald-500 text-white' : 'border-slate-300 bg-white' }}" aria-label="Toggle task">@if($task->completed_at)✓@endif</button></form><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><p class="text-sm font-semibold {{ $task->completed_at ? 'text-slate-400 line-through' : 'text-slate-800' }}">{{ $task->title }}</p><span class="rounded-full px-2 py-0.5 text-xs font-semibold {{ $task->priority === 'high' ? 'bg-red-50 text-red-700' : ($task->priority === 'low' ? 'bg-slate-100 text-slate-600' : 'bg-amber-50 text-amber-700') }}">{{ ucfirst($task->priority) }}</span></div>@if($task->description)<p class="mt-1 text-xs text-slate-500">{{ $task->description }}</p>@endif @if($task->due_date)<p class="mt-1 text-xs {{ !$task->completed_at && $task->due_date->isPast() ? 'font-semibold text-red-600' : 'text-slate-400' }}">Due {{ $task->due_date->format('d M Y') }}</p>@endif</div><form action="{{ route('events.tasks.destroy', [$event, $task]) }}" method="POST">@csrf @method('DELETE')<button class="text-xs font-semibold text-red-600">Remove</button></form></div>@endforeach</div>@endif
        </section>

        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between gap-4"><div><h2 class="font-semibold text-slate-900">Announcements</h2><p class="mt-1 text-sm text-slate-500">Send an in-app update to registered students.</p></div><span class="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-semibold text-indigo-700">{{ $event->status->label() }}</span></div>
            @if($event->status === \App\Enums\EventStatus::Published)<form action="{{ route('events.announcements.store', $event) }}" method="POST" class="mt-5 space-y-3 rounded-xl bg-indigo-50 p-4">@csrf<input name="title" value="{{ old('title') }}" required maxlength="255" class="block w-full rounded-lg border border-indigo-200 p-2.5 text-sm" placeholder="Announcement title"><textarea name="message" required rows="4" maxlength="3000" class="block w-full rounded-lg border border-indigo-200 p-2.5 text-sm" placeholder="What should participants know?">{{ old('message') }}</textarea><button class="w-full rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Send to {{ $event->registered_count }} student(s)</button></form>@else<div class="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Announcements become available after an administrator publishes this event.</div>@endif
            @if($event->announcements->isEmpty())<p class="mt-6 rounded-xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500">No announcements sent yet.</p>@else<div class="mt-5 space-y-3">@foreach($event->announcements as $announcement)<article class="rounded-xl border border-slate-200 p-4"><div class="flex items-start justify-between gap-3"><div><h3 class="text-sm font-semibold text-slate-800">{{ $announcement->title }}</h3><p class="mt-1 text-xs text-slate-400">{{ $announcement->published_at->format('d M Y, H:i') }}</p></div><form action="{{ route('events.announcements.destroy', [$event, $announcement]) }}" method="POST">@csrf @method('DELETE')<button class="text-xs font-semibold text-red-600">Remove</button></form></div><p class="mt-3 whitespace-pre-line text-sm leading-6 text-slate-600">{{ $announcement->message }}</p></article>@endforeach</div>@endif
        </section>
    </div>
</x-layouts.app>
