@php($editing = isset($commitment))
<x-form-errors />
<form action="{{ $editing ? route('commitments.update', $commitment) : route('commitments.store') }}" method="POST" class="space-y-6">@csrf @if($editing) @method('PUT') @endif
    <div class="grid gap-6 md:grid-cols-2">
        <div class="md:col-span-2"><label for="title" class="mb-2 block text-sm font-medium text-slate-700">Title</label><input id="title" name="title" value="{{ old('title', $commitment->title ?? '') }}" required maxlength="255" class="block w-full rounded-lg border border-slate-300 p-2.5 text-sm" placeholder="e.g. Software Engineering lecture"></div>
        <div><label for="commitment_type" class="mb-2 block text-sm font-medium text-slate-700">Type</label><select id="commitment_type" name="commitment_type" required class="block w-full rounded-lg border border-slate-300 p-2.5 text-sm">@foreach(['class' => 'Class', 'test' => 'Test or exam', 'meeting' => 'Meeting', 'study' => 'Study block', 'personal' => 'Personal'] as $value => $label)<option value="{{ $value }}" @selected(old('commitment_type', $commitment->commitment_type ?? 'personal') === $value)>{{ $label }}</option>@endforeach</select></div>
        <div><label for="location" class="mb-2 block text-sm font-medium text-slate-700">Location</label><input id="location" name="location" value="{{ old('location', $commitment->location ?? '') }}" maxlength="255" class="block w-full rounded-lg border border-slate-300 p-2.5 text-sm" placeholder="Room, building, or online"></div>
        <div><label for="starts_at" class="mb-2 block text-sm font-medium text-slate-700">Starts</label><input id="starts_at" name="starts_at" type="datetime-local" value="{{ old('starts_at', isset($commitment) ? $commitment->starts_at->format('Y-m-d\TH:i') : request('starts_at')) }}" required class="block w-full rounded-lg border border-slate-300 p-2.5 text-sm"></div>
        <div><label for="ends_at" class="mb-2 block text-sm font-medium text-slate-700">Ends</label><input id="ends_at" name="ends_at" type="datetime-local" value="{{ old('ends_at', isset($commitment) ? $commitment->ends_at->format('Y-m-d\TH:i') : request('ends_at')) }}" required class="block w-full rounded-lg border border-slate-300 p-2.5 text-sm"></div>
        <div class="md:col-span-2"><label for="description" class="mb-2 block text-sm font-medium text-slate-700">Notes</label><textarea id="description" name="description" rows="4" maxlength="2000" class="block w-full rounded-lg border border-slate-300 p-2.5 text-sm" placeholder="Optional details">{{ old('description', $commitment->description ?? '') }}</textarea></div>
    </div>
    <div class="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-blue-800">Commitments are added even if they overlap another item, but the conflict will be clearly highlighted on your calendar.</div>
    <div class="flex flex-wrap justify-between gap-3 border-t border-slate-100 pt-5"><div>@if($editing)<button type="submit" form="delete-commitment" class="rounded-lg px-4 py-2.5 text-sm font-semibold text-red-600 hover:bg-red-50">Delete commitment</button>@endif</div><div class="flex gap-3"><a href="{{ route('calendar.index', ['month' => isset($commitment) ? $commitment->starts_at->format('Y-m') : now()->format('Y-m')]) }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Cancel</a><button class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">{{ $editing ? 'Update commitment' : 'Add commitment' }}</button></div></div>
</form>
@if($editing)<form id="delete-commitment" action="{{ route('commitments.destroy', $commitment) }}" method="POST" onsubmit="return confirm('Delete this commitment?')">@csrf @method('DELETE')</form>@endif
