<x-layouts.app title="Personal calendar">
    <x-page-header title="Personal calendar" description="Registered events and personal commitments in one conflict-aware timeline."><a href="{{ route('commitments.create') }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Add commitment</a></x-page-header>

    <div class="mb-6 flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><a href="{{ route('calendar.index', ['month' => $previousMonth]) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700">← Previous</a><div class="text-center"><p class="text-lg font-bold text-slate-900">{{ $month->format('F Y') }}</p><p class="text-xs text-slate-500">{{ $entries->count() }} calendar {{ Str::plural('item', $entries->count()) }}</p></div><a href="{{ route('calendar.index', ['month' => $nextMonth]) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700">Next →</a></div>

    <div class="mb-5 flex flex-wrap gap-4 rounded-xl bg-slate-100 px-4 py-3 text-xs text-slate-600"><span class="flex items-center gap-2"><span class="h-2.5 w-2.5 rounded-full bg-indigo-500"></span>Registered event</span><span class="flex items-center gap-2"><span class="h-2.5 w-2.5 rounded-full bg-emerald-500"></span>Personal commitment</span><span class="flex items-center gap-2"><span class="h-2.5 w-2.5 rounded-full bg-red-500"></span>Overlapping item</span></div>

    @if($entries->isEmpty())
        <x-empty-state title="Nothing scheduled in {{ $month->format('F') }}" description="Registered events and personal commitments for this month will appear here."><a href="{{ route('commitments.create') }}" class="text-sm font-semibold text-indigo-600">Add a commitment →</a></x-empty-state>
    @else
        <div class="space-y-5">@foreach($entriesByDate as $date => $dayEntries)<section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="border-b border-slate-100 bg-slate-50 px-6 py-3"><p class="text-sm font-semibold text-slate-800">{{ \Carbon\Carbon::parse($date)->format('l, d F') }}</p></header><div class="divide-y divide-slate-100">@foreach($dayEntries as $entry)<a href="{{ $entry['url'] }}" class="flex flex-wrap items-center gap-4 px-6 py-5 hover:bg-slate-50"><div class="w-28 shrink-0"><p class="font-semibold text-slate-900">{{ $entry['starts_at']->format('H:i') }}</p><p class="text-xs text-slate-500">to {{ $entry['ends_at']->format($entry['ends_at']->isSameDay($entry['starts_at']) ? 'H:i' : 'd M, H:i') }}</p></div><span class="h-10 w-1 rounded-full {{ $entry['has_conflict'] ? 'bg-red-500' : ($entry['kind'] === 'event' ? 'bg-indigo-500' : 'bg-emerald-500') }}"></span><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><p class="font-semibold text-slate-900">{{ $entry['title'] }}</p>@if($entry['has_conflict'])<span class="rounded-full bg-red-50 px-2 py-0.5 text-xs font-semibold text-red-700">Schedule clash</span>@endif</div><p class="mt-1 text-xs text-slate-500">{{ $entry['kind'] === 'event' ? 'Registered event' : 'Personal commitment' }} · {{ $entry['subtitle'] }}</p></div><span class="text-xs font-semibold text-indigo-600">{{ $entry['kind'] === 'event' ? 'Details' : 'Edit' }} →</span></a>@endforeach</div></section>@endforeach</div>
    @endif
</x-layouts.app>
