@php($editing = isset($timeslot))
<x-form-errors />
<form action="{{ $editing ? route('timeslots.update', $timeslot) : route('timeslots.store') }}" method="POST" class="space-y-6">
    @csrf
    @if ($editing) @method('PUT') @endif
    <div class="grid gap-6 md:grid-cols-3">
        <div><label for="slot_date" class="mb-2 block text-sm font-medium text-slate-700">Date</label><input id="slot_date" name="slot_date" type="date" value="{{ old('slot_date', $timeslot->slot_date ?? '') }}" required class="block w-full rounded-lg border border-slate-300 p-2.5 text-sm focus:border-indigo-500 focus:ring-indigo-500"></div>
        <div><label for="start_time" class="mb-2 block text-sm font-medium text-slate-700">Start hour</label><select id="start_time" name="start_time" required class="block w-full rounded-lg border border-slate-300 p-2.5 text-sm focus:border-indigo-500 focus:ring-indigo-500"><option value="">Select</option>@for($hour = 8; $hour < 23; $hour++)<option value="{{ sprintf('%02d:00', $hour) }}" @selected(old('start_time', isset($timeslot) ? substr($timeslot->start_time, 0, 5) : '') === sprintf('%02d:00', $hour))>{{ \Carbon\Carbon::createFromTime($hour)->format('g:00 A') }}</option>@endfor</select></div>
        <div><label for="end_time" class="mb-2 block text-sm font-medium text-slate-700">End hour</label><select id="end_time" name="end_time" required class="block w-full rounded-lg border border-slate-300 p-2.5 text-sm focus:border-indigo-500 focus:ring-indigo-500"><option value="">Select</option>@for($hour = 9; $hour <= 23; $hour++)<option value="{{ sprintf('%02d:00', $hour) }}" @selected(old('end_time', isset($timeslot) ? substr($timeslot->end_time, 0, 5) : '') === sprintf('%02d:00', $hour))>{{ \Carbon\Carbon::createFromTime($hour)->format('g:00 A') }}</option>@endfor</select></div>
    </div>
    <label class="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><input name="is_outside_working_hours" type="checkbox" value="1" @checked(old('is_outside_working_hours', isset($timeslot) && substr($timeslot->end_time, 0, 2) > 18)) class="mt-0.5 rounded border-amber-300 text-amber-600"><span class="text-sm text-amber-800"><strong>Outside normal working hours</strong><br>Required for a timeslot that ends after 6:00 PM. Extended timeslots may finish by 11:00 PM.</span></label>
    <div class="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">Timeslots must start and end on the hour. Organizers choose the hours used for their venue requests.</div>
    <div class="flex justify-end gap-3 border-t border-slate-200 pt-5"><a href="{{ route('timeslots.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancel</a><button class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700">{{ $editing ? 'Update timeslot' : 'Create timeslot' }}</button></div>
</form>
