<x-layouts.app title="Student dashboard">
    <x-page-header title="Student dashboard" description="Welcome, {{ auth()->user()->name }}. Discover events and keep track of your registrations."><a href="{{ route('discover.index') }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Discover events</a></x-page-header>

    <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-4">
        <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-sm font-medium text-slate-500">My events</p><p class="mt-2 text-3xl font-bold text-slate-900">{{ $registeredCount }}</p><a href="{{ route('my-events.index') }}" class="mt-2 inline-flex text-xs font-semibold text-indigo-600">View registrations →</a></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-sm font-medium text-slate-500">Available events</p><p class="mt-2 text-3xl font-bold text-slate-900">{{ $publishedCount }}</p><a href="{{ route('discover.index') }}" class="mt-2 inline-flex text-xs font-semibold text-indigo-600">Browse catalogue →</a></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-sm font-medium text-slate-500">Commitments</p><p class="mt-2 text-3xl font-bold text-slate-900">{{ $commitmentCount }}</p><a href="{{ route('calendar.index') }}" class="mt-2 inline-flex text-xs font-semibold text-indigo-600">Open calendar →</a></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-sm font-medium text-slate-500">Unread notifications</p><p class="mt-2 text-3xl font-bold text-slate-900">{{ $unreadNotificationCount }}</p><a href="{{ route('notifications.index') }}" class="mt-2 inline-flex text-xs font-semibold text-indigo-600">Open inbox →</a></div>
    </div>

    <div class="mt-6 grid gap-6 lg:grid-cols-2">
        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="font-semibold text-slate-900">Next registered event</h2><p class="mt-1 text-sm text-slate-500">Your earliest confirmed event.</p></div><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">Live</span></div>@if($nextRegistration)@php($schedule = $nextRegistration->event->schedules->first())<div class="mt-6 rounded-xl bg-slate-50 p-5"><h3 class="font-semibold text-slate-900">{{ $nextRegistration->event->title }}</h3><p class="mt-2 text-sm text-slate-600">{{ $schedule->timeslot->slot_date->format('d M Y') }} · {{ substr($schedule->timeslot->start_time, 0, 5) }} · {{ $schedule->venue->name }}</p></div>@else<div class="mt-6 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center text-sm text-slate-500">You have not registered for an event yet.</div>@endif</section>
        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="font-semibold text-slate-900">Personal calendar</h2><p class="mt-1 text-sm text-slate-500">Registered events and personal commitments in one timeline.</p></div><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">Live</span></div><div class="mt-6 rounded-xl bg-indigo-50 p-6"><p class="text-sm leading-6 text-slate-700">Add classes, tests, meetings, study blocks, and personal commitments. The calendar highlights overlapping entries before they surprise you.</p><a href="{{ route('calendar.index') }}" class="mt-4 inline-flex text-sm font-semibold text-indigo-700">Open calendar →</a></div></section>
    </div>
</x-layouts.app>
