@php($editing = isset($schedule))
<x-form-errors />
<form action="{{ $editing ? route('schedules.update', $schedule) : route('schedules.store') }}" method="POST" class="space-y-6">
    @csrf
    @if ($editing) @method('PUT') @endif
    <div class="grid gap-6 md:grid-cols-2">
        <div class="md:col-span-2"><label for="event_id" class="mb-2 block text-sm font-medium text-slate-700">Event</label><select id="event_id" name="event_id" required class="block w-full rounded-lg border border-slate-300 bg-white p-2.5 text-sm focus:border-indigo-500 focus:ring-indigo-500"><option value="">Select an event</option>@foreach ($events as $event)<option value="{{ $event->id }}" @selected(old('event_id', $schedule->event_id ?? '') == $event->id)>{{ $event->title }} · {{ number_format($event->capacity) }} attendees</option>@endforeach</select></div>
        <div><label for="venue_id" class="mb-2 block text-sm font-medium text-slate-700">Venue</label><select id="venue_id" name="venue_id" required class="block w-full rounded-lg border border-slate-300 bg-white p-2.5 text-sm focus:border-indigo-500 focus:ring-indigo-500"><option value="">Select a venue</option>@foreach ($venues as $venue)<option value="{{ $venue->id }}" @selected(old('venue_id', $schedule->venue_id ?? '') == $venue->id)>{{ $venue->name }} · {{ number_format($venue->capacity) }} seats</option>@endforeach</select></div>
        <div><label for="timeslot_id" class="mb-2 block text-sm font-medium text-slate-700">Timeslot</label><select id="timeslot_id" name="timeslot_id" required class="block w-full rounded-lg border border-slate-300 bg-white p-2.5 text-sm focus:border-indigo-500 focus:ring-indigo-500"><option value="">Select a timeslot</option>@foreach ($timeslots as $timeslot)<option value="{{ $timeslot->id }}" @selected(old('timeslot_id', $schedule->timeslot_id ?? '') == $timeslot->id)>{{ $timeslot->slot_date }} · {{ $timeslot->start_time }}–{{ $timeslot->end_time }}</option>@endforeach</select></div>
        <div><label for="status" class="mb-2 block text-sm font-medium text-slate-700">Schedule source</label><select id="status" name="status" required class="block w-full rounded-lg border border-slate-300 bg-white p-2.5 text-sm focus:border-indigo-500 focus:ring-indigo-500"><option value="manual" @selected(old('status', $schedule->status ?? 'manual') === 'manual')>Manual</option><option value="generated" @selected(old('status', $schedule->status ?? '') === 'generated')>Generated</option></select><p class="mt-1.5 text-xs text-slate-500">GA generation will be implemented in a later phase.</p></div>
    </div>
    <div class="rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-sm leading-6 text-indigo-800"><strong>Validation:</strong> the event must fit the venue, may only be scheduled once, and cannot overlap another booking at the same venue.</div>
    <div class="flex justify-end gap-3 border-t border-slate-200 pt-5"><a href="{{ route('schedules.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancel</a><button class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700">{{ $editing ? 'Update schedule' : 'Create schedule' }}</button></div>
</form>
