<x-layouts.app title="Attendance · {{ $event->title }}">
    <x-page-header title="Attendance: {{ $event->title }}" description="Open a secure QR check-in window and monitor participation in real time."><a href="{{ route('analytics.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">View analytics</a></x-page-header>
    <x-form-errors />
    @php($rate = $event->registered_count ? round($event->attended_count / $event->registered_count * 100) : 0)
    <div class="mb-6 grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Registered</p><p class="mt-2 text-3xl font-bold text-slate-900">{{ $event->registered_count }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Checked in</p><p class="mt-2 text-3xl font-bold text-emerald-600">{{ $event->attended_count }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Attendance rate</p><p class="mt-2 text-3xl font-bold text-indigo-600">{{ $rate }}%</p></div></div>

    <div class="grid gap-6 xl:grid-cols-5"><section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm xl:col-span-2"><h2 class="font-semibold text-slate-900">QR check-in session</h2>@if($session?->isOpen())<div class="mt-5 rounded-xl bg-slate-50 p-4 text-center"><img src="{{ $qrCode }}" alt="Attendance QR code" class="mx-auto h-auto w-full max-w-xs"><p class="mt-3 text-sm font-semibold text-emerald-700">Open until {{ $session->closes_at->format('H:i') }}</p><p class="mt-1 text-xs text-slate-500">Students scan, sign in, and confirm attendance.</p></div><form action="{{ route('events.attendance.sessions.close', [$event, $session]) }}" method="POST" class="mt-4">@csrf @method('PATCH')<button class="w-full rounded-lg border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-600">Close session now</button></form>@else<div class="mt-5 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5 text-sm text-slate-600">No active session. Opening a session creates a new random, time-limited QR code.</div>@if($event->status === \App\Enums\EventStatus::Published)<form action="{{ route('events.attendance.sessions.store', $event) }}" method="POST" class="mt-4">@csrf<label for="duration_minutes" class="mb-2 block text-sm font-medium text-slate-700">Check-in window</label><select id="duration_minutes" name="duration_minutes" class="block w-full rounded-lg border border-slate-300 p-2.5 text-sm"><option value="15">15 minutes</option><option value="30" selected>30 minutes</option><option value="60">1 hour</option><option value="120">2 hours</option></select><button class="mt-3 w-full rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Open attendance session</button></form>@else<p class="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Only published events can open a new session.</p>@endif @endif</section>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm xl:col-span-3"><div class="border-b border-slate-100 p-6"><h2 class="font-semibold text-slate-900">Participant register</h2><p class="mt-1 text-sm text-slate-500">QR and manually recorded check-ins.</p>@if($session?->isOpen() && $registrations->whereNull('attendanceRecord')->isNotEmpty())<form action="{{ route('events.attendance.manual', [$event, $session]) }}" method="POST" class="mt-4 flex gap-2">@csrf<select name="registration_id" required class="min-w-0 flex-1 rounded-lg border border-slate-300 p-2.5 text-sm"><option value="">Select student for manual check-in</option>@foreach($registrations->whereNull('attendanceRecord') as $registration)<option value="{{ $registration->id }}">{{ $registration->user->name }} · {{ $registration->user->email }}</option>@endforeach</select><button class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Record</button></form>@endif</div>@if($registrations->isEmpty())<p class="p-6 text-sm text-slate-500">No registered students.</p>@else<div class="divide-y divide-slate-100">@foreach($registrations as $registration)<div class="flex items-center justify-between gap-4 px-6 py-4"><div><p class="text-sm font-semibold text-slate-800">{{ $registration->user->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $registration->user->email }}</p></div>@if($registration->attendanceRecord)<div class="text-right"><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">Present</span><p class="mt-1 text-xs text-slate-400">{{ $registration->attendanceRecord->checked_in_at->format('H:i') }} · {{ strtoupper($registration->attendanceRecord->method) }}</p></div>@else<span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-500">Not checked in</span>@endif</div>@endforeach</div>@endif</section></div>
</x-layouts.app>
