<x-layouts.app title="Venue requests">
    <x-page-header title="Venue requests" description="Track requested venue assignments and their approval status.">@if(auth()->user()->hasRole('organizer'))<a href="{{ route('venue-requests.create') }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">New request</a>@endif</x-page-header>
    @if ($requests->isEmpty())<x-empty-state title="No venue requests" description="Approved event venue requests will appear here." />@else
        <div class="space-y-4">@foreach($requests as $venueRequest)<article class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="font-semibold text-slate-900">{{ $venueRequest->event->title }}</h2><p class="mt-1 text-sm text-slate-500">{{ $venueRequest->venue->name }} · {{ $venueRequest->timeslot->slot_date->format('d M Y') }}, {{ substr($venueRequest->timeslot->start_time, 0, 5) }}–{{ substr($venueRequest->timeslot->end_time, 0, 5) }}</p><p class="mt-1 text-xs text-slate-400">Requested by {{ $venueRequest->requester->name }}</p></div><span class="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-semibold text-indigo-700">{{ $venueRequest->status->label() }}</span></div>
            @if($venueRequest->organizer_notes)<p class="mt-4 text-sm text-slate-600">Organizer: {{ $venueRequest->organizer_notes }}</p>@endif
            @if($venueRequest->admin_notes)<p class="mt-2 rounded-lg bg-slate-50 p-3 text-sm text-slate-700">Administrator: {{ $venueRequest->admin_notes }}</p>@endif
            @if(auth()->user()->hasRole('administrator') && $venueRequest->status === \App\Enums\VenueRequestStatus::Pending)<div class="mt-5 grid gap-3 border-t border-slate-100 pt-4 md:grid-cols-2"><form action="{{ route('venue-requests.approve', $venueRequest) }}" method="POST" class="flex gap-2">@csrf @method('PATCH')<input name="admin_notes" class="min-w-0 flex-1 rounded-lg border border-slate-300 p-2.5 text-sm" placeholder="Optional approval notes"><button class="rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">Approve</button></form><form action="{{ route('venue-requests.reject', $venueRequest) }}" method="POST" class="flex gap-2">@csrf @method('PATCH')<input name="admin_notes" required class="min-w-0 flex-1 rounded-lg border border-slate-300 p-2.5 text-sm" placeholder="Required rejection reason"><button class="rounded-lg bg-red-600 px-4 py-2.5 text-sm font-semibold text-white">Reject</button></form></div>@endif
        </article>@endforeach</div>
    @endif
</x-layouts.app>
